"""Domain integrity: types, limits, domains, defaults, identity, generated columns."""
import pytest

from cexgen.schema import Family, QName

pytestmark = pytest.mark.db


def test_families_and_limits(model_of):
    m = model_of("""
    CREATE TABLE t (
        a smallint, b bigint, c numeric(8,2), d numeric, e real, f varchar(40), g char(3), h "char",
        i text, j boolean, k date, l time(3), m timestamptz(0), n interval, o uuid, p json, q jsonb,
        r bytea, s inet, u bit(4), v varbit(8), w point, x money, y tsvector
    );
    """)
    c = m.table("t").columns
    assert (c["a"].type.family, c["a"].type.min_value, c["a"].type.max_value) == (Family.INTEGER, -32768, 32767)
    assert c["b"].type.max_value == 9223372036854775807
    assert (c["c"].type.precision, c["c"].type.scale) == (8, 2)
    assert c["d"].type.precision is None
    assert c["e"].type.family == Family.FLOAT
    assert (c["f"].type.length, c["f"].type.varying) == (40, True)
    assert (c["g"].type.length, c["g"].type.varying) == (3, False)
    assert c["i"].type.length is None
    assert c["l"].type.precision == 3 and c["l"].type.with_time_zone is False
    assert c["m"].type.precision == 0 and c["m"].type.with_time_zone is True
    assert (c["p"].type.binary_json, c["q"].type.binary_json) == (False, True)
    assert (c["u"].type.length, c["v"].type.varying) == (4, True)
    assert [c[k].type.family for k in "orswx"] == [Family.UUID, Family.BYTES, Family.NETWORK, Family.GEOMETRIC,
                                                   Family.MONEY]
    assert c["y"].type.family == Family.OTHER
    assert any("t.y" in w and "no value rules" in w for w in m.warnings)


def test_negative_numeric_scale(model_of, settings):
    m = model_of("CREATE TABLE t (x numeric(5, -2));")
    if m.server_version < 150000:
        pytest.skip("negative scale needs PostgreSQL 15")
    assert (m.table("t").columns["x"].type.precision, m.table("t").columns["x"].type.scale) == (5, -2)


def test_enum_and_arrays(model_of):
    m = model_of("""
    CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy');
    CREATE TYPE nothing AS ENUM ();
    CREATE TABLE t (a mood, b mood[], c varchar(5)[], d int[][], e nothing);
    """)
    c = m.table("t").columns
    assert c["a"].type.enum_labels == ("sad", "ok", "happy")
    assert c["b"].type.family == Family.ARRAY and c["b"].type.element.enum_labels == ("sad", "ok", "happy")
    assert c["c"].type.element.length == 5                     # modifier belongs to the element
    assert c["d"].type.dimensions == 2 and c["d"].type.element.family == Family.INTEGER
    assert any("no labels" in w for w in m.warnings)


def test_nested_domains_carry_checks_and_not_null(model_of):
    m = model_of("""
    CREATE DOMAIN positive AS numeric(8,2) NOT NULL CHECK (VALUE > 0);
    CREATE DOMAIN small AS positive CHECK (VALUE < 1000);
    CREATE DOMAIN codes AS varchar(3)[];
    CREATE TABLE t (price small, cs codes, "Value" int);
    """)
    t = m.table("t")
    price = t.columns["price"]
    assert price.type.family == Family.NUMERIC and price.type.precision == 8
    assert price.type.domains == (QName("public", "small"), QName("public", "positive"))
    assert not price.nullable
    exprs = {c.name: c.expression for c in t.all_checks}
    assert exprs["positive_check"] == "price > 0::numeric"
    assert "price" in exprs["small_check"] and "VALUE" not in exprs["small_check"]
    assert t.columns["cs"].type.family == Family.ARRAY and t.columns["cs"].type.element.length == 3


def test_ranges_and_composites(model_of):
    m = model_of("""
    CREATE TYPE addr AS (street text, zip char(5));
    CREATE TABLE t (r int4range, d tsrange, a addr);
    """)
    c = m.table("t").columns
    assert c["r"].type.family == Family.RANGE and c["r"].type.subtype.family == Family.INTEGER
    assert c["a"].type.family == Family.COMPOSITE
    assert [n for n, _ in c["a"].type.fields] == ["street", "zip"]
    assert c["a"].type.fields[1][1].length == 5


def test_defaults_identity_generated_serial(model_of):
    m = model_of("""
    CREATE TABLE t (
        id serial PRIMARY KEY,
        a int GENERATED ALWAYS AS IDENTITY,
        b int GENERATED BY DEFAULT AS IDENTITY,
        c int DEFAULT 5,
        d int GENERATED ALWAYS AS (c * 2) STORED
    );
    """)
    c = m.table("t").columns
    assert c["id"].is_serial and c["id"].has_default
    assert (c["a"].identity, c["b"].identity) == ("always", "by default")
    assert c["c"].default == "5"
    assert c["d"].generated == "c * 2" and not c["d"].insertable and c["d"].default is None
    assert [x.name for x in m.table("t").insertable_columns] == ["id", "a", "b", "c"]


def test_dropped_columns_ignored_and_positions_kept(model_of):
    m = model_of("CREATE TABLE t (a int, b int, c int); ALTER TABLE t DROP COLUMN b;")
    cols = m.table("t").columns
    assert list(cols) == ["a", "c"] and cols["c"].position == 3


def test_extension_type(model_of):
    m = model_of("CREATE EXTENSION IF NOT EXISTS citext; CREATE TABLE t (e citext);")
    t = m.table("t").columns["e"].type
    assert t.family == Family.TEXT and t.extension == "citext"


def test_collation_recorded_only_when_explicit(model_of):
    m = model_of('CREATE TABLE t (a text, b text COLLATE "C", c text COLLATE "POSIX");')
    cols = m.table("t").columns
    assert cols["a"].collation is None and cols["c"].collation == "POSIX"
